#!/bin/bash

# a simple game to guess the number generated by the script :) #

PSQL="psql --username=freecodecamp --dbname=number_guess -t --no-align -c"

# login function
LOGIN() {

  echo -e "\nEnter your username:"
  read USERNAME

  USER_ID=$($PSQL "SELECT user_id FROM users WHERE username='$USERNAME'")

  
  if [[ -z $USER_ID ]]
  then
    # if is a new user then add in the database
    ADD_USER=$($PSQL "INSERT INTO users(username) VALUES('$USERNAME')")
    USER_ID=$($PSQL "SELECT user_id FROM users WHERE username='$USERNAME'")
    echo -e "\nWelcome, $USERNAME! It looks like this is your first time here."
  else 
    # else, get from database the count of games played and the best game
    GAMES_PLAYED=$($PSQL "SELECT count(user_id) FROM games WHERE user_id='$USER_ID'")
    BEST_GAME=$($PSQL "SELECT min(guesses) FROM games WHERE user_id='$USER_ID' ")
    echo -e "Welcome back, $USERNAME! You have played $GAMES_PLAYED games, and your best game took $BEST_GAME guesses."
  fi

}

# number guess function
NUMBER_GUESS() {
  # generate the secret random number
  SECRET_NUMBER=$(($RANDOM % 1000 + 1))
  echo "Guess the secret number between 1 and 1000:"
  read USER_NUMBER
  COUNTER=1

  while [[ $USER_NUMBER != $SECRET_NUMBER ]]
  do
    # if input is not a integer
    if ! [[ $USER_NUMBER =~ ^[0-9]+$ ]]
    then
      echo -e "That is not an integer, guess again:"
      read USER_NUMBER
    else
      # if the secret number is lower than input
      if [[ $USER_NUMBER > $SECRET_NUMBER ]]
      then
        echo -e "It's lower than that, guess again:"
        let COUNTER++
        read USER_NUMBER
      else
        # if the secret number is higher than input
        echo -e "It's higher than that, guess again:"
        let COUNTER++
        read USER_NUMBER
      fi
    fi
  done

  # final message with number of tries and the reveal of secret number
  echo -e "You guessed it in $COUNTER tries. The secret number was $SECRET_NUMBER. Nice job!"

  # insert number of tries in a new row in games table
  INSERT_GUESSES=$($PSQL "INSERT INTO games(user_id, guesses) VALUES('$USER_ID','$COUNTER')")

  # By Caballou 🐴

}

LOGIN
NUMBER_GUESS